<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Administrator extends Model
{
    /** @use HasFactory<\Database\Factories\AdministratorFactory> */
    use HasFactory;

    protected $fillable = [
        'user_id',
        'first_name',
        'last_name',
        'university_email',
        'is_super_admin',
    ];

    protected $casts = [
        'is_super_admin' => 'boolean',
    ];

    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();

        static::saving(function ($admin) {
            // If this admin is being set as super admin, remove super admin flag from all other admins
            if ($admin->is_super_admin) {
                static::where('id', '!=', $admin->id)
                    ->where('is_super_admin', true)
                    ->update(['is_super_admin' => false]);
            }
        });
    }

    /**
     * Get the user that owns the admin profile.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the internship agreements generated by the admin.
     */
    public function internshipAgreements()
    {
        return $this->hasMany(InternshipAgreement::class, 'admin_id');
    }

    /**
     * Check if this admin is the super admin.
     */
    public function isSuperAdmin(): bool
    {
        return $this->is_super_admin;
    }
}
